AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template for a single-instance bastion host'
Parameters:
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
  EnvironmentType:
    Description: "Specify which env to run in"
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
  LatestAmiId:
    Type:  'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  KeyName:
    Description: Name of an existing EC2 KeyPair for SSH
    Type: AWS::EC2::KeyPair::KeyName

Mappings:
  EnvironmentTypeToInstanceType:
    dev:
      InstanceType: t2.nano
    test:
      InstanceType: t2.micro
    prod:
      InstanceType: t2.small

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  Subnet10:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      VpcId: !Ref VPC
      CidrBlock: 10.0.10.0/24
      MapPublicIpOnLaunch: true
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  InternetRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGateway
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable
  Subnet10RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet10
  BastionInstance:
  # Incident Response Playbook
  # 1. Create automated alerts that display unusual behaviors from host.
  # 2. Isolate host from network traffic if there is a threat.
  # To do this- moify the 'SecurityGroups' property below to replace the current
  # security group with the 'IsolatedSecurityGroup', remove '- !Ref InboundAccessSecurityGroup'
  # and replace it with '- !Ref IsolatedSecurityGroup'
  # 3. Perserve logs for evidence.
  # 4. Anaylze logs.
  # 5. Delete the instance, ensure SSH keyfairs are updated.
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: !Ref LatestAmiId
      InstanceType:
        !FindInMap [EnvironmentTypeToInstanceType, !Ref EnvironmentType, InstanceType]
      # Rule for inside the network that alows for shell access.
      SecurityGroups: 
        - !Ref 'InboundAccessSecurityGroup'
      KeyName: !Ref 'KeyName'
  InboundAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow inbound tcp on SSH port"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

  #New group that isolates the bastion host from any communication within the VPC or public Internet.
  IsolatedSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Group to isolate the bastion host from internal VPC/public internet"

Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'BastionInstance'
  URI:
    Description: URI that points to public SSH end point
    Value: !Sub ssh://${BastionInstance.PublicDnsName}

